const COLLECTIONS_TO_ANALYZE = 7;
const MAX_TOTAL_SUPPLY = 10000;
const MIN_FLOOR_PRICE = 0.01;
const MIN_VOLUME = 20;
const PROTOCOLS = ['ERC721', 'ERC1155'];

module.exports = {
  COLLECTIONS_TO_ANALYZE,
  MAX_TOTAL_SUPPLY,
  MIN_FLOOR_PRICE,
  MIN_VOLUME,
  PROTOCOLS,
};
