name: Github CI

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TELEGRAM_ACCESS_TOKEN: ${{ secrets.TELEGRAM_ACCESS_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: node:18.12.1-alpine3.15

    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run lint

      - run: npm test

      - run: npm audit --audit-level=high

      - name: Setup Fly.io config
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only

      - name: Set Telegram webhook callback URL
        run: npm run telegram-webhook:set https://apeiner.fly.dev/webhooks/telegram
